---
- name: AdGuard Unterordner für Volumes erstellen
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ adguard_install_path }}"
    - "{{ adguard_conf_dir }}"
    - "{{ adguard_work_dir }}"

- name: AdGuard docker-compose.yml erstellen
  template:
    src: docker-compose.yml.j2
    dest: "{{ adguard_install_path }}/docker-compose.yml"

- name: AdGuard Container starten
  command: docker compose up -d
  args:
    chdir: "{{ adguard_install_path }}"