---
  - name: Verzeichnis für Keys erstellen
    file:
      path: /etc/apt/keyrings
      state: directory
      mode: '0755'

  - name: Docker GPG Key laden
    get_url:
      url: https://download.docker.com/linux/debian/gpg
      dest: /etc/apt/keyrings/docker.asc

  - name: Docker Repo hinzufügen
    apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
      state: present

  - name: Installation von den Paketen
    apt:
      name:
        - docker-ce
        - docker-compose-plugin
        - curl
        - zip
        - msmtp
        - msmtp-mta
        - mpack
      state: present
      update_cache: yes

  - name: Hauptordner für vaultwarden
    file:
      path: /opt/vaultwarden
      state: directory
      mode: '0755'

  - name: docker-compose.yml
    copy:
      dest: /opt/vaultwarden/docker-compose.yml
      content: |
        services:
          vaultwarden:
            image: vaultwarden/server:latest
            container_name: vaultwarden
            restart: always
            environment:
              - WEBSOCKET_ENABLED=true
            volumes:
              - ./vw-data:/data
            ports:
              - "8080:80"

  - name: Container starten
    command: docker compose up -d
    args:
      chdir: /opt/vaultwarden

#Vaultwarden-Backup und Cronjob einrichten

  - name: MSMTP Konfiguration
    copy:
      dest: /etc/msmtprc
      owner: root
      group: root
      mode: '0600'
      content: |
        defaults
        auth           on
        tls            on
        tls_trust_file /etc/ssl/certs/ca-certificates.crt
        logfile        /var/log/msmtp.log

        account        default
        host           {{ smtp_host }}
        port           {{ smtp_port }}
        from           {{ smtp_user }}
        user           {{ smtp_user }}
        password       {{ smtp_token }}

  - name: Backup-Skript erstellen
    copy:
      dest: /usr/local/bin/vaultwarden_backup.sh
      mode: '0700'
      content: |
        #!/bin/bash
        TIMESTAMP=$(date +%Y-%m-%d)
        BACKUP_FILE="/tmp/vaultwarden_backup.zip"
        
        cd /opt/vaultwarden && docker compose stop
        
        zip -r -P {{ backup_zip_password }} $BACKUP_FILE /opt/vaultwarden/vw-data
        
        docker compose start
        
        mpack -s "Vaultwarden Backup $TIMESTAMP" $BACKUP_FILE {{ mail_to }}

        rm $BACKUP_FILE

  - name: Wöchentlichen Cronjob
    cron:
      name: "Wöchentliches Vaultwarden Backup"
      minute: "0"
      hour: "3"
      weekday: "1"
      job: "/usr/local/bin/vaultwarden_backup.sh"