---
  - name: Installation von den Paketen
    apt:
      name:
        - docker-ce
        - docker-compose-plugin
        - curl
        - zip
        - msmtp
        - msmtp-mta
        - mpack
      state: present
      update_cache: yes

  - name: Hauptordner für vaultwarden
    file:
      path: '{{ vault_install_path }}'
      state: directory
      mode: '0755'

  - name: docker-compose.yml erstellen
    template:
      src: docker-compose.yml.j2
      dest: "{{ vault_install_path }}/docker-compose.yml"
      mode: '0644'
        

  - name: Container starten
    command: docker compose up -d
    args:
      chdir: '{{ vault_install_path }}'

#Vaultwarden-Backup und Cronjob einrichten

  - name: MSMTP Konfiguration
    template:
      src: msmtp.yml.j2
      dest: /etc/msmtprc
      owner: root
      group: root
      mode: '0600'

  - name: Backup-Skript erstellen
    template:
      src: backup-script.yml.j2
      dest: /usr/local/bin/vaultwarden_backup.sh
      owner: root
      group: root
      mode: '0700'

  - name: Wöchentlichen Cronjob
    cron:
      name: "Wöchentliches Vaultwarden Backup"
      minute: "0"
      hour: "3"
      weekday: "1"
      job: "/usr/local/bin/vaultwarden_backup.sh"