---
- name: Affine Unterordner für Volumes erstellen
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ affine_install_path }}"
    - "{{ affine_upload_location }}"
    - "{{ affine_config_location }}"
    - "{{ affine_db_data_location }}"

- name: docker-compose.yml erstellen
  template:
    src: docker-compose.yml.j2
    dest: "{{ affine_install_path }}/docker-compose.yml"
    mode: '0644'
      

- name: Container starten
  command: docker compose up -d
  args:
    chdir: '{{ affine_install_path }}'