---
jellyfin_version: "12.1"
halcyon_version: "0.20.2"
halcyon_image: "halcyon-video:{{ halcyon_version }}-c8384c6"
halcyon_watch_region: "DE"
halcyon_youtube_channels: "{{ lookup('env', 'HALCYON_YOUTUBE_CHANNELS') }}"

jellyfin_install_path: "/opt/jellyfin"
jellyfin_config_dir: "/opt/jellyfin/config"
jellyfin_cache_dir: "/opt/jellyfin/cache"
jellyfin_media_dir: "/opt/jellyfin/media"

jellyfin_port: 8096
halcyon_port: 1420

jellyfin_render_gid: 104

domain_name: "{{ lookup('env', 'DOMAIN_NAME') }}"
jellyfin_subdomain: "{{ lookup('env', 'JELLYFIN_SUBDOMAIN') }}"
halcyon_subdomain: "{{ lookup('env', 'HALCYON_SUBDOMAIN') }}"
