---
- name: Hauptordner für traefik
  file:
    path: '{{ docker_dest }}'
    state: directory
    mode: '0755'

- name: Hauptordner für traefik-config
  file:
    path: '{{ config_dest }}'
    state: directory
    mode: '0755'
    
- name: Erstelle leere acme.json mit richtigen Rechten (600)
  file:
    path: '{{ docker_dest }}/acme.json'
    state: touch
    mode: '0600'

- name: Erstelle Traefik Dynamic Configs
  template:
    src: "{{ item.src }}"
    dest: "{{ config_dest }}/{{ item.dest }}"
  loop:
    - { src: 'vaultwarden.yml.j2', dest: 'vaultwarden.yml' }
    - { src: 'nextcloud.yml.j2', dest: 'nextcloud.yml' }
    - { src: 'office-nextcloud.yml.j2', dest: 'office.yml' }
    - { src: 'affine.yml.j2', dest: 'affine.yml' }
    - { src: 'immich.yml.j2', dest: 'immich.yml' }
    - { src: 'paperless.j2', dest: 'paperless.yml' }
    - { src: 'finance.yml.j2', dest: 'finance.yml' }
    - { src: 'ntfy.yml.j2', dest: 'ntfy.yml' }

- name: Traefik Haupt-Konfigurationen erstellen
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_dest }}/{{ item.dest }}"
  loop:
    - { src: 'docker_compose.yml.j2', dest: 'docker-compose.yml' }
    - { src: 'traefik.yml.j2', dest: 'traefik.yml' } 

- name: Container starten
  command: docker compose up -d
  args:
    chdir: '{{ docker_dest }}'