---
- name: paperless-ngx Gruppe erstellen
  group:
    name: paperless-ngx
    system: yes
    state: present

- name: paperless-ngx Benutzer erstellen
  user:
    name: paperless-ngx
    group: paperless-ngx
    system: yes
    shell: /bin/bash
    create_home: yes

- name: paperless-ngx Ordnerstruktur erstellen
  file:
    path: "{{ item }}"
    state: directory
    owner: paperless-ngx
    group: paperless-ngx
    mode: '0755'
  loop:
    - "{{ paperless_install_path }}"
    - "{{ paperless_install_path }}/data"
    - "{{ paperless_install_path }}/media"
    - "{{ paperless_install_path }}/export"
    - "{{ paperless_install_path }}/consume"
    - "{{ paperless_install_path }}/scripts"
    - "{{ paperless_proton_data }}"

- name: Python Skript (ai_tagger.py) auf den Server kopieren
  copy:
    src: ai_tagger.py
    dest: "{{ paperless_install_path }}/scripts/ai_tagger.py"
    owner: paperless-ngx
    group: paperless-ngx
    mode: '0755'


- name: proton-bridge Build-Context (Dockerfile) kopieren
  copy:
    src: proton-bridge
    dest: "{{ paperless_install_path }}/"
    owner: paperless-ngx
    group: paperless-ngx
    mode: '0644'

- name: paperless-ngx docker-compose.yml erstellen
  template:
    src: docker-compose.yml.j2
    dest: "{{ paperless_install_path }}/docker-compose.yml"

- name: paperless-ngx Container starten
  command: docker compose up -d --build
  args:
    chdir: "{{ paperless_install_path }}"