[adguard]
192.168.178.30 ansible_user=root

[traefik]
192.168.178.31 ansible_user=root

[cloudflared]
192.168.178.32 ansible_user=root

[monitoring]
192.168.178.60 ansible_user=root

[collabora]
192.168.178.81 ansible_user=root

[vaultwarden]
192.168.178.82 ansible_user=root

[affine]
192.168.178.83 ansible_user=root

[immich]
192.168.178.84 ansible_user=root

[qwen3]
192.168.178.85 ansible_user=root

[consul]
192.168.178.63 ansible_user=root

[debian_guests:children]
adguard
traefik
cloudflared
monitoring
collabora
vaultwarden
affine
immich
qwen3
consul