---
- name: Setup vaultwarden
  hosts: vaultwarden
  become: yes

  tasks:
    - name: System update und upgrade
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes

    - name: Verzeichnis für Keys erstellen
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Docker GPG Key laden
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Docker Repo hinzufügen
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present

    - name: Installation von den Paketen
      apt:
        name:
          - docker-ce
          - docker-compose-plugin
          - curl
        state: present
        update_cache: yes

    - name: Hauptordner für vaultwarden
      file:
        path: /opt/vaultwarden
        state: directory
        mode: '0755'

    - name: docker-compose.yml
      copy:
        dest: /opt/vaultwarden/docker-compose.yml
        content: |
          services:
            vaultwarden:
              image: vaultwarden/server:latest
              container_name: vaultwarden
              restart: always
              environment:
                - WEBSOCKET_ENABLED=true
              volumes:
                - ./vw-data:/data
              ports:
                - "8080:80"

    - name: Container starten
      command: docker compose up -d
      args:
        chdir: /opt/vaultwarden