---
- name: Basis-Konfiguration für alle Server
  hosts: proxmox_all_lxc, proxmox_all_qemu, !Nextcloud, !Kali-Linux-Prax
  become: yes
  roles:
    - common

- name: Setup Vaultwarden Dienst
  hosts: tag_vaultwarden
  become: yes
  roles:
    - vaultwarden

- name: Setup Traefik Config Dienst
  hosts: tag_traefik
  become: yes
  roles:
    - traefik

- name: Setup Collabora Dienst
  hosts: tag_collabora
  become: yes
  roles:
    - collabora

- name: Setup Affine Dienst
  hosts: tag_affine
  become: yes
  roles:
    - affine

- name: Setup Adguard Dienst
  hosts: tag_adguard
  become: yes
  roles:
    - adguard

- name: Setup Cloudflared Dienst
  hosts: tag_cloudflared
  become: yes
  roles:
    - cloudflared

- name: Setup Monitoring Dienst
  hosts: tag_monitoring
  become: yes
  roles:
    - monitoring

- name: Setup Immich Dienst
  hosts: tag_immich
  become: yes
  roles:
    - immich

- name: Setup Paperless Dienst
  hosts: tag_paperless
  become: yes
  roles:
    - paperless

- name: Setup Actual-Budget Dienst
  hosts: tag_actual_budget
  become: yes
  roles:
    - finance

- name: Deploy node-exporter to all guest VMs
  hosts: proxmox_all_lxc, proxmox_all_qemu, !Nextcloud, !Kali-Linux-Prax