domain_name: "domain.de"
vault_subdomain: "subdomain"
vault_internal_ip: "XXX.XXX.XXX.XXX"
vault_internal_port: "8080"
backup_zip_password: "XXXXX"
smtp_host: "XXX"
smtp_port: "587"
smtp_user: "XXX@XXX"
smtp_token: "XXXX"
mail_to: "XXX@XXX"