---
#Docker-Compose
CF_DNS_API_TOKEN: "XXXXXXX"
CF_API_TOKEN: "XXXXXXX"
subdomain: "XXXXXX"
docker_dest: "/opt/traefik"

#Let's Encrypt Email
email_letsEncrypt: "XXXX@XXX"

#Config destination
config_dest: "/opt/traefik/config"

#Vaultwarden
vault_subdomain: "subdomain"
vault_internal_ip: "XXX.XXX.XXX.XXX"
vault_internal_port: "8080"

#Affine
affine_subdomain: "subdomain"
affine_internal_ip: "XXX.XXX.XXX.XXX"
affine_internal_port: "3010"

#Nextcloud
nextcloud_subdomain: "subdomain"
nextcloud_internal_ip: "XXX.XXX.XXX.XXX"

#Office-Nextcloud
office_subdomain: "subdomain"
office_internal_ip: "XXX.XXX.XXX.XXX"
office_internal_port: "9980"

#Immich
immich_subdomain: "subdomain"
immich_internal_ip: "XXX.XXX.XXX.XXX"
immich_internal_port: "2283"
