---
affine_install_path: "/opt/affine"

# Affine Container-Einstellungen
affine_revision: 'stable'
affine_port: '3010'

# Pfade für die Volumes auf dem LXC-Server
affine_upload_location: '/opt/affine/storage'
affine_config_location: '/opt/affine/config'
affine_db_data_location: '/opt/affine/postgres'

# Datenbank-Zugangsdaten
affine_db_username: "{{ lookup('env', 'affine_db_username') }}"
affine_db_password: "{{ lookup('env', 'affine_db_password') }}"
affine_db_database: "{{ lookup('env', 'affine_db_database') }}"
